### ISSUE TITLE
Differentiate between sub-flow and connector nodes

### ISSUE THREAD

**Issue by manikmagar** [manikmagar/mulefd#122]
When connectors are [registered as known](https://github.com/manikmagar/mulefd#known-modulesconnectors), they are rendered same as sub-flow.

Here is an example of rendering object store component - 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/877286/95667808-0c293280-0b39-11eb-9943-7b4e1d46a040.png">

One alternative is, to use `component` style to render registered connectors. For example -
<img width="614" alt="image" src="https://user-images.githubusercontent.com/877286/95667753-5362f380-0b38-11eb-942b-ab001d037b82.png">

Possibly, the `path` registered can also be displayed, like on the sources.

**Comment by mark-knox** [comment]
I like the compent-style rendering as it set's it apart more from the other container types.  Not sure if the path would be necessary but just calling it out would be helpful.
