### ISSUE TITLE
Display scheduled flows as such

### ISSUE THREAD

**Issue by ChristianLangmann** [manikmagar/mulefd#301]
Scheduled flows are not displayed with a source, so they look like they are never called. 
A scheduler can be either displayed as a source (though without path or config), or a flow could be marked (with an icon or a different color)

**Comment by ChristianLangmann** [comment]
Yes, thought about it. Problem could be that then probably all flows are triggered by the identical scheduler, because the scheduler doesn't have a sensible path. We could use the name, frequency or the doc:id, but the name/freq is often not unique, and the there is no point in printing doc:id as the path. Therefore I thought about handling scheduler as something different than a "normal" source.

**Comment by manikmagar** [comment]
Yes, Schedulers do not have any config or path. Doc id/name should not be used for anything except documenting. In general, the source graphical representations should stay consistent for all source elements. In general, schedulers with cron expression (with property placeholder) is a best/preferred practice. I think we could use the cron expression value as a path value. If any implementation doesn't use cron, then the diagram can at least help uncover that and move to cron for better representation in the diagram. 

What do you have in mind for "something different than a "normal" source"?

**Comment by manikmagar** [comment]
PR #304 adds the support for mule core components. Here is a rendered diagram for scheduler flows. 

![image](https://user-images.githubusercontent.com/877286/200196997-159182a8-634d-4dbe-a331-3c6e253cac57.png)

Scheduler element does not have any path-eligible attribute at the element level. Using `scheduling-strategy -> cron -> expression` will get enabled with #296 Allow Complex Path feature.

```xml
<scheduler doc:name="Scheduler" doc:id="8a2088ba-a947-438c-97e5-b124f4386b18" >
	<scheduling-strategy >
		<cron expression="${cron.expreesion}" />
	</scheduling-strategy>
</scheduler>
```
