### ISSUE TITLE
Is muleflowdiagrams as a command too verbose to type?

### ISSUE THREAD

**Issue by manikmagar** [manikmagar/mulefd#63]
Is `muleflowdiagrams` as a command too verbose to type every time? 

Feels like. Alternative names could - `mulefd` or just `mfd`. Any other names?

**Comment by ajdeguzman** [comment]
I thought of this too. `mulefd` will do to stay descriptive and signify that this is a mule related command. Cheers!

**Comment by ryandcarter** [comment]
I vote mfd

**Comment by manikmagar** [comment]
Thanks for sharing your thoughts @ajdeguzman  @ryandcarter .

`mfd` is so far the shortest abbrevation. I tried searching another cli with possibly that name but nothing came up yet. That doesn't mean it may not exist but.

**Comment by manikmagar** [comment]
Staying within Mule context and renaming project to `mulefd`.
